### ISSUE TITLE
How to add discard to the crypttab and others improvements

### ISSUE THREAD

**Issue by FRodrigues42** [wmutschl/website-academic#10]
Hello,
I was following the Pop!_OS 20.04 with btrfs-LVM-luks installation guide and now Pop!_OS already has a newer kernel version how do we enable discard?

```
$ uname -a
Linux pop-os 5.11.0-7612-generic #13~1617215757~20.04~97a8d1a-Ubuntu SMP Thu Apr 1 21:15:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

In my case, I saw this guide https://wiki.debian.org/SSDOptimization and added `,discard` to `/etc/crypttab` cryptdata line.

Also following that guide I changed the scheduler to be `dead-line`:
```
$ grep . /sys/block/sd?/queue/scheduler
[mq-deadline] none
```

Were it good changes?

**Comment by FRodrigues42** [comment]
When I installed stuff with flatpak and apt my system would freeze. 
So I removed qgroups from timeshift disabled quotas and now apt are doing fine. 
Then I also removed discard and flatpaks now they are much better but it still freezes a bit.

**Comment by wmutschl** [comment]
As Pop!_OS is based on Ubuntu you have to add `,discard` to your crypttab. I just installed 21.04 and uploaded a guide for that where I hinted towards this. I never saw much difference by changing the scheduler, so at some point I stopped experimenting with this and simply took the default, so I can't say whether that was a good change or not.

Regarding your occasional slowdowns/freezes: I have no idea what is going on, for me it is working fine and I don't have such freezes, but you are not alone: https://forum.manjaro.org/t/freeze-issues-with-btrfs-and-timeshift/22005/11
