### ISSUE TITLE
How to setup BTRBK

### ISSUE THREAD

**Issue by giraldiego** [wmutschl/website-academic#11]
Hello, your guide has helped me a lot from my transition from pop os to Fedora in the past few days.
Could you please add some information in the page about your backup strategy in regards to BTRBK?
I already did setup  my system with @ and @home, and have Timeshift working as intended. But I haven't been able to make BTRBK to work. I want to replicate your backup on the internal drive on your linux machine:
Dell Precision 7520 (Fedora Linux)
3. hourly, daily, weekly and monthly BTRFS send/receive snapshots to the internal 512GB SSD drive using BTRBK (automatic)

I also have an internal drive formated to BTRFS, and with a subvolume named fedora. Trying to emulate the author's setup for **Example: Backups to USB Disk**:

- a backup disk having a btrfs volume mounted as /mnt/btr_backup, containing a subvolume or directory mylaptop for the incremental backups.

Just sharing your btfbk.conf will help me a lot.

**Comment by wmutschl** [comment]
I think you should have a look at https://mutschler.eu/linux/backup/ the conf files and scripts are in this repo: https://github.com/wmutschl/scripts
