### ISSUE TITLE
Home folder not properly set up on Pop!_OS 21.04

### ISSUE THREAD

**Issue by Herschenglime** [wmutschl/website-academic#14]
Hello! Thanks for making such a comprehensive guide! I ran into an (fixable) issue in the process which may need your attention.

Following the "Pop!_OS 20.04 with btrfs-LVM-luks installation guide and auto-apt snapshots with Timeshift" guide for 21.04 results in the user that is set up by the pop os installer not having a home directory, with the $HOME variable instead being set to the root directory. This causes various issues.

I'm not sure what in the installation process causes this, but the issue can be easily worked around by switching to a tty and making a new user account, giving it sudo privileges, and then removing the first one.

If one were to know this going in, they could make the account in the installer a temporary one that would only be used to create their main account, bypassing the headache of creating a second account to delete the first with the username that you wanted to use and then making a 3rd one with said username.

**Comment by S0PEX** [comment]
I think that I run into the same issue as after following the tutorial I wasn't able to open Firefox ( profile folder doesn't exists error ) and also running `apt upgrade` failed.
Would also be quite interested in a fix that doesn't require to create a new user.

**Comment by Herschenglime** [comment]
Yeah, Firefox doesn't have a config folder to put user info and cache and whatnot so it fails to open

**Comment by S0PEX** [comment]
I think it might be sufficient to run `sudo usermod -d /home/username username`. I will perform a test setup and test it later.

**Comment by wmutschl** [comment]
Thanks for working this out, I am in the process of finally checking out the new Pop!OS and will follow the merged guide!
