### ISSUE TITLE
Files are missing following guide

### ISSUE THREAD

**Issue by crzsotona** [wmutschl/website-academic#5]
Hi,

I tried to follow guide to install ubuntu on btrfs with luks, and on optional step 3 there are no /usr/lib/partman/mount.d/70btrfs and /usr/lib/partman/fstab.d/btrfs.
I'm using Ubuntu20.04.1 server.

Maybe guide should be updated?

**Comment by crzsotona** [comment]
I think this issue is incorrect as I was trying to adapt guide to user-data btrfs encrypted partition.

**Comment by cirrusflyer** [comment]
Can you elaborate on this?  I have the same issue in Ubuntu desktop.  Not sure I understand your explanation of why these folders wouldn't exist.  Thanks

**Comment by crzsotona** [comment]
> Can you elaborate on this? I have the same issue in Ubuntu desktop. Not sure I understand your explanation of why these folders wouldn't exist. Thanks

Because it's pre-installation step while I was setting partition on already installed Ubuntu system.

**Comment by cirrusflyer** [comment]
Thanks.  Mine is a fresh install, and I still don't have these folders.
