### ISSUE TITLE
Receiving Syntax error on Pop Gnome Terminal Theme section when attempting to add lines to .bashrc

### ISSUE THREAD

**Issue by vectorcr** [wmutschl/website-academic#6]
On :: website-academic/content/linux/install-guides/fedora-post-install.md :: section // Pop Gnome Terminal Theme

When attempting to follow the guide I receive a syntax error on lines that include "fi". When changing  fi to if I receive "line 69: syntax error: unexpected end of file"

**Comment by wmutschl** [comment]
You should not change `fi` to `if`. In bash, you begin an if statement by `if` and end it with `fi`. Could you retry with `fi` and sent me both the exact error message as well as the output of `cat /home/$USER/.bashrc` so I can have a look?
