### ISSUE TITLE
Fedora 33/timeshift guide issues

### ISSUE THREAD

**Issue by manpreetszr** [wmutschl/website-academic#7]
I've tried this a few times and have always ended up in emergency mode from which I failed to recover. The following things are unclear in the guide:

1. What are `Meta`+`Term`+`Enter` keys supposed to be.. specifically the `Term` key?
2. The `/btrfs_pool` and related `/etc/fstab` operations read like they are being done on a live system. Wouldn't that be leading to data corruption and maybe the emergency mode issue?

**Comment by CrustyB** [comment]
>     2. The `/btrfs_pool` and related `/etc/fstab` operations read like they are being done on a live system. Wouldn't that be leading to data corruption and maybe the emergency mode issue?

This issue.  It is like he missed an instruction to chroot, except fedora doesn't have chroot.

**Comment by wmutschl** [comment]
- Meta is the super/windows key
- term means just start typing term after hitting the meta key
- when you hit meta, start writing term you will have searched for terminal in gnome, hitting enter opens the terminal

**Comment by wmutschl** [comment]
You can rename your btrfs subvolumes on a running system, but you have to be careful to not miss a thing. It is better to do so in a live system.
Actually, I have a fork of timeshift that works with a default fedora btrfs install, checkout my fork of timeshift on gihtub.
